### ISSUE TITLE
Insert progress bar while base import

### ISSUE THREAD

**Issue by sbilxxxx** [adansons/base#19]
# Motivation
Show the user how much more time it will take to import the data to decrease frustration.

# Description
Show progress bar while importing dataset in CLI.
The progress information can be % or anything else.

# Additional context (optional)

**Comment by kenichihiguchi** [comment]
@31159piko-suke 
can you make this?

**Comment by 31159piko-suke** [comment]
ok!  I will get it done  by the end of this week.
