### ISSUE TITLE
cannot export CSV file by `base search... --export CSV`

### ISSUE THREAD

**Issue by ynntech** [adansons/base#25]
# Expected behavior
Export CSV file by `base search... --export CSV`

# Error messages, stack traces, or logs
Cannot export to CSV when the extracted table value contains int type.
`TypeError: sequence item xxx: expected str instance, int found`

# Steps to reproduce
 Need code to cast to type str before exporting.

**Comment by kenichihiguchi** [comment]
let's solve this in next version 0.1.1 on this sunday!
