### ISSUE TITLE
No support for Japanese external files.

### ISSUE THREAD

**Issue by ynntech** [adansons/base#27]
Before using the post method, 
we should encode the data to utf8 like below at project.py https://github.com/adansons/base/blob/955d5edff5666776127e049bf4c7ebc9444391b2/base/project.py

```python
data = data.encode('utf-8')
res = requests.post(url, json.dumps(data), headers=HEADER)
```

**Comment by kenichihiguchi** [comment]
It seems good to encode data after `json.dumps()`.
```Python
res = requests.post(url, json.dumps(data).encode('utf-8'), headers=HEADER)
```
