### ISSUE TITLE
operated Files object can not filter properly

### ISSUE THREAD

**Issue by YU-SUKETAKAHASHI** [adansons/base#57]
# Error messages, stack traces, or logs
I concatenate FIles object. 
```python
project = Project("glia")
files1 = project.files(conditions="20220418", query=["hour >= 018"], sort_key='hour')
files2 = project.files(conditions="20220419", sort_key='hour')
files3 = project.files(conditions="20220420", query=["hour <= 009"], sort_key='hour')
files = files1 + files2 + files3
```

Then I filter the concatenated Files, but it is not work. 
```python
filtered_files = files.filter(query=['hour > 020'])
print(len(filtered_files))
>>> 0
```

The bug is caused by the `.query` attribute of the concatenated `Files`.
Because the `.query` attributes of `files1` and `files3` are also concatenated, there is no `File` that satisfies these queries.
```python
print(files.query)
>>>['hour >= 018', 'hour <= 009']
```

# Steps to reproduce
~~I think the concatenated `Files` should have the empty `.query` attribute.~~
~~`Files` is already queried, so the elements itself has query information.~~  ~~Hence filtered `Files` don't have to remember its query.~~

I will change not to concatenate queries in `filter` method.
https://github.com/adansons/base/blob/dev/base/files.py#L222
```
filtered_files.query = query + self.query
```
↓
```
filtered_files.query = query
```

# Additional context (optional)

**Comment by 31159piko-suke** [comment]
thanks!
I will use query specfied by user instead of filtered_files.query in __query_filter method.

https://github.com/adansons/base/blob/main/base/files.py#L230

```python
if len(query) > 0:
            result = filtered_files.__query_filter(result, filtered_files.query)
```
↓

```python
if len(query) > 0:
            result = filtered_files.__query_filter(result, query)
```
---
Then attriburtes of `conditons` and `query` is not needed, so I think I will remove it from Files Class.
We will discuss this change in more detail in #59.
